### ISSUE TITLE
xsel support

### ISSUE THREAD

**Issue by Link-Satonaka** [chilicuil/vim-sprunge#11]
xclip and xsel are very similar, and I'd prefer to not have to install xclip while I already use xsel. Would you consider adding xsel support? Thanks

**Comment by chilicuil** [comment]
Hi,

That's a good idea, I've added support for xsel in 3ec0255c1e522f1829439b2e8e34a20c63dd69cb , I've used `xsel -bi` to copy to the CLIPBOARD selection to emulate xclip|pbcopy.

I've also added a new option, `g:sprunge_clipboard_cmd` to avoid keep adding clipboard applications, so, if no xsel support had been added you still could use it this way:

`let g:sprunge_clipboard_cmd='xsel -bi'`

Let me know if you have any issue.

**Comment by Link-Satonaka** [comment]
Thank you for adding this, and also for the external command. I am satisfied, but for the sake of completion you might want to have xsel respond to the g:sprunge_clipboard variable, instead of being hardcoded to the clipboard.

**Comment by chilicuil** [comment]
Not sure what you're referring to, the g:sprunge_clipboard variable accepts any of 4 parameters, "none", "vim", "external", "all", in the case of "external" and "all" parameters a handful of external clipboards are tried, xclip, xsel and pbcopy, so I think xsel kind of respond to the g:sprunge_clipboard variable, if the hardcoded way of calling xsel (of any external clipboard) doesn't fit your workflow, you can customize it with g:sprunge_clipboard_cmd which is executed after everything.

**Comment by Link-Satonaka** [comment]
Oh, I misunderstood the purpose the the variable. I thought "external" and "all" might have been referring to "clipboard" and "primary selection", respectively.
