### ISSUE TITLE
Autoorient code on left border before pasting

### ISSUE THREAD

**Issue by mightyCelu** [chilicuil/vim-sprunge#12]
When pasting indented code, it would be great to orient it on the left border, such that the indentation that's not justified by just the codeblock being posted is removed.

Example:
```
int main() {
    if (condition) {
         printf("Hello World\n”);
    }
    return 0;
}
```
When selecting and pasting lines 2-4, it should be pasted as:
```
if (condition) {
    printf("Hello World\n”);
}
```

**Comment by chilicuil** [comment]
Hello @mightyCelu, 

That sounds nice, although I wouldn't integrate it in the default behavior, I like it more as an option. I'll see if I can come up with something during the weekend, pretty much still learning vim scripting =)

**Comment by mightyCelu** [comment]
Hi @chilicuil, That's great! I also think it's better to make it opt-in. Otherwise it might the expected behavior for some users.

**Comment by chilicuil** [comment]
Hello @mightyCelu 

I've just added a barbarian implementation of the suggested feature, it's disabled by default, to test it add:

`let g:sprunge_flush_left = 1`

To your vimrc file, please let me know if you find any issue.
