### ISSUE TITLE
Feature: Support ix.io ?

### ISSUE THREAD

**Issue by jakejohns** [chilicuil/vim-sprunge#13]
sprunge is down rupa/sprunge#35
ix.io is quite similar rupa/sprunge#10
@rupa seems frustrated with the hosting situation for sprunge.

Maybe this could possibly support http://ix.io as well?
```vim
command! -range=% IX  silent execute <line1> . "," . <line2> . "w !curl -F 'f:1=<-' ix.io | tr -d '\\n' | xclip -i -selection clipboard"
```
[from reddit](https://www.reddit.com/r/vim/comments/3wffwm/pastery_another_vim_plugin/)

.... I guess it kinnda already does with:
```vim
 let g:sprunge_cmd = 'curl -s -F "f:1=<-" http://ix.io'
```
However, there are other fancy features, and the syntax highlight is not a query in ix.io.

**Comment by chilicuil** [comment]
Hello @jakejohns,

Indeed, updating the `g:sprunge_cmd` variable is an option, however the plugin should just work, I'll probably add an option for providers, so if one of them fails it continue with the following...

```vim
let g:sprunge_providers = "sprunge,ix,etc"
```

If you've a better idea feel free to share it.

**Comment by jakejohns** [comment]
that sounds reasonable. Looping until it finds one seems a like it'll be a bit of performance hit waiting for the last one if it's the only one up. But bumping the preferred/functioning one to the front of the list is no different than designating a single one, and will be more resilient. 

noting here also that sprunge.vim:84 needs to be updated for ix.io highlighting:
```vim
if g:sprunge_open_browser | call sprunge#OpenBrowser(l:url . '/' . &filetype) | endif
"                                                             ^ / instead of ?
```
Although I think you can post the file type as well, and just get the url back with it.

**Comment by chilicuil** [comment]
it could be both @jakejohns, by default it could use
```vim
let g:sprunge_providers = "sprunge,ix,etc"
```

But users could configure
```vim
let g:sprunge_providers = "ix" 
```
Or 
```vim
 let g:sprunge_cmd = 'curl -s -F "f:1=<-" http://ix.io'
```

If they only want to use a single or custom service, still not sure about highlighting, probably will end writing a wrapper function to modify the generated url before calling `sprunge#OpenBrowser()`

**Comment by chilicuil** [comment]
Hello @jakejohns 

I've added an initial implementation of the suggested feature, it's working on my side, but feel free to comment any issue.

**Comment by jakejohns** [comment]
Cool! I'll check it out. Thanks!
I'll close this and reopen if necessary.
Thanks again!
