### ISSUE TITLE
mapping already exists

### ISSUE THREAD

**Issue by Link-Satonaka** [chilicuil/vim-sprunge#8]
There's a new error with the latest update

`Error detected while processing C:\Users\Link\vimfiles\bundle\vim-sprunge\plugin\sprunge.vim:
line 40: E227: mapping already exists for \s`

This pops up every time I start vim

**Comment by chilicuil** [comment]
Hi,

Thank you for your report, indeed there is an error but that's the expected behavior, Sprunge sets its default mapping either by mapping directly to the `<Plug>Sprunge` public function, e.g.

    map <leader>s <Plug>Sprunge

Or by setting the `g:sprunge_map` variable, e.g:

    let g:sprunge_map = '<Leader>s'

If none of that happen it defines g:sprunge_map = '<Leader>s' but will refuse to override it if the mapping is already taken. I think a message is better than being quite and keep Sprunge unmapped.

I suggest you to review your .vimrc file to see where the <Leader>s mapping is set and remove it or to customize the Sprunge default mapping.

If enough persons think is better to stay quite and just don't define any mapping when the default mapping is taken I'll modify it.

**Comment by Link-Satonaka** [comment]
Unfortunately the error is not that simple. I do not have any <Leader>s mapping. I use vundle, and the error does not appear when I comment out `Bundle 'chilicuil/vim-sprunge'` from my rc file. There is some incompatibility with vundle and sprunge.

**Comment by chilicuil** [comment]
If you've not defined the mapping yourself it could be a conflict with other plugin, try commenting all your plugins but vundle & sprunge and see if the problem persist.

If you prefer to just avoid the message and use this plugin with `:Sprunge` add `silent! ` just before `map` and `xmap` in https://github.com/chilicuil/vim-sprunge/blob/master/plugin/sprunge.vim#L39-L40

**Comment by Link-Satonaka** [comment]
I set a new profile, a new empty vimrc (only including what is required for vundle to install sprung), and the issue persists.

![clipboard01](https://cloud.githubusercontent.com/assets/4342746/5894167/42bff6b4-a4cc-11e4-834a-f1457b996de7.png)

**Comment by chilicuil** [comment]
That's kind of weird, which vundle/shundle reversion are you running?, also, could please post a minimal vimrc file where the issue still persists?

**Comment by Link-Satonaka** [comment]
http://sprunge.us/iZKd

**Comment by chilicuil** [comment]
Hey,

I tried your minimal configuration and wasn't able to reproduce the error (in Ubuntu 12.04), it just starts fine. Give it a try to `map` to see if you can find to whom the mapping was assigned.

**Comment by Link-Satonaka** [comment]
It says that there is no mapping for <Leader>s, something strange is happening.
The previous version worked perfectly, but in addition to this error message there is another problem with this update: it takes two minutes for the sprunge command to complete (where previously it would finish in seconds).

**Comment by chilicuil** [comment]
I'm starting to think it may be related to `<unique>`, `<Plug>` and the Windows vim version, the latest commit wasn't really big https://github.com/chilicuil/vim-sprunge/commit/31a159df73d54b455ce02c92d14f28ba80866a53 so I don't see other variables who could create this conflict.

Unfortunately I've no access to a Windows machine, so I cannot debug further this issue. If you find more debugging information who could help to resolve this mystery that would be fine. In the meantime you can checkout the previous revision with `git checkout b8fba7d` (inside the vim-sprunge directory) or use a vundle clone with revision locking support (such as [Neobundle](https://github.com/Shougo/neobundle.vim))

**Comment by chilicuil** [comment]
Hi,

Could you test https://github.com/MatthewClair/vim-sprunge and see if it fixes the issue for you?

Best regards

**Comment by Link-Satonaka** [comment]
That one works just fine- no error message, finishes within 2 seconds.

**Comment by chilicuil** [comment]
Thanks for your input and sorry for the long wait, please keep opening more reports if you find more issues.
